# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class DeployV5(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(DeployV5, self).__init__()
        self.module_0 = py_nndct.nn.Input() #DeployV5::input_0(DeployV5::nndct_input_0)
        self.module_1 = py_nndct.nn.Input() #DeployV5::input_1(DeployV5::nndct_input_1)
        self.module_2 = py_nndct.nn.Conv2d(in_channels=3, out_channels=16, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[0]/ret.5(DeployV5::nndct_conv2d_2)
        self.module_3 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[2]/ret.9(DeployV5::nndct_relu_3)
        self.module_4 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/MaxPool2d[3]/2806(DeployV5::nndct_maxpool_4)
        self.module_5 = py_nndct.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[4]/ret.11(DeployV5::nndct_conv2d_5)
        self.module_6 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[6]/ret.15(DeployV5::nndct_relu_6)
        self.module_7 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/MaxPool2d[7]/2850(DeployV5::nndct_maxpool_7)
        self.module_8 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[8]/ret.17(DeployV5::nndct_conv2d_8)
        self.module_9 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[10]/ret.21(DeployV5::nndct_relu_9)
        self.module_10 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[11]/ret.23(DeployV5::nndct_conv2d_10)
        self.module_11 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[13]/ret.27(DeployV5::nndct_relu_11)
        self.module_12 = py_nndct.nn.AvgPool2d(kernel_size=[16, 32], stride=[16, 32], padding=[0, 0], ceil_mode=False, count_include_pad=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/AvgPool2d[14]/2921(DeployV5::nndct_avgpool_12)
        self.module_13 = py_nndct.nn.Conv2d(in_channels=3, out_channels=16, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[0]/ret.29(DeployV5::nndct_conv2d_13)
        self.module_14 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[2]/ret.33(DeployV5::nndct_relu_14)
        self.module_15 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/MaxPool2d[3]/2965(DeployV5::nndct_maxpool_15)
        self.module_16 = py_nndct.nn.Conv2d(in_channels=16, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[4]/ret.35(DeployV5::nndct_conv2d_16)
        self.module_17 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[6]/ret.39(DeployV5::nndct_relu_17)
        self.module_18 = py_nndct.nn.MaxPool2d(kernel_size=[2, 2], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/MaxPool2d[7]/3009(DeployV5::nndct_maxpool_18)
        self.module_19 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[8]/ret.41(DeployV5::nndct_conv2d_19)
        self.module_20 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[10]/ret.45(DeployV5::nndct_relu_20)
        self.module_21 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/Conv2d[11]/ret.47(DeployV5::nndct_conv2d_21)
        self.module_22 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/ReLU[13]/ret.51(DeployV5::nndct_relu_22)
        self.module_23 = py_nndct.nn.AvgPool2d(kernel_size=[16, 32], stride=[16, 32], padding=[0, 0], ceil_mode=False, count_include_pad=True) #DeployV5::DeployV5/DeployEyeCNN[eye_cnn]/Sequential[features]/AvgPool2d[14]/3080(DeployV5::nndct_avgpool_23)
        self.module_24 = py_nndct.nn.Cat() #DeployV5::DeployV5/ret.53(DeployV5::nndct_concat_24)
        self.module_25 = py_nndct.nn.Conv2d(in_channels=128, out_channels=96, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[shared]/Conv2d[0]/ret.55(DeployV5::nndct_conv2d_25)
        self.module_26 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/Sequential[shared]/ReLU[1]/ret.57(DeployV5::nndct_relu_26)
        self.module_27 = py_nndct.nn.Conv2d(in_channels=96, out_channels=48, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[regression_head]/Conv2d[0]/ret.59(DeployV5::nndct_conv2d_27)
        self.module_28 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/Sequential[regression_head]/ReLU[1]/ret.61(DeployV5::nndct_relu_28)
        self.module_29 = py_nndct.nn.Conv2d(in_channels=48, out_channels=2, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[regression_head]/Conv2d[2]/ret.63(DeployV5::nndct_conv2d_29)
        self.module_30 = py_nndct.nn.Conv2d(in_channels=96, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[horizontal_head]/Conv2d[0]/ret.65(DeployV5::nndct_conv2d_30)
        self.module_31 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/Sequential[horizontal_head]/ReLU[1]/ret.67(DeployV5::nndct_relu_31)
        self.module_32 = py_nndct.nn.Conv2d(in_channels=32, out_channels=3, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[horizontal_head]/Conv2d[2]/ret.69(DeployV5::nndct_conv2d_32)
        self.module_33 = py_nndct.nn.Conv2d(in_channels=96, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[vertical_head]/Conv2d[0]/ret.71(DeployV5::nndct_conv2d_33)
        self.module_34 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/Sequential[vertical_head]/ReLU[1]/ret.73(DeployV5::nndct_relu_34)
        self.module_35 = py_nndct.nn.Conv2d(in_channels=32, out_channels=3, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[vertical_head]/Conv2d[2]/ret.75(DeployV5::nndct_conv2d_35)
        self.module_36 = py_nndct.nn.Conv2d(in_channels=96, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[geometry_head]/Conv2d[0]/ret.77(DeployV5::nndct_conv2d_36)
        self.module_37 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/Sequential[geometry_head]/ReLU[1]/ret.79(DeployV5::nndct_relu_37)
        self.module_38 = py_nndct.nn.Conv2d(in_channels=32, out_channels=4, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[geometry_head]/Conv2d[2]/ret.81(DeployV5::nndct_conv2d_38)
        self.module_39 = py_nndct.nn.Sigmoid() #DeployV5::DeployV5/Sequential[geometry_head]/Sigmoid[3]/ret.83(DeployV5::nndct_sigmoid_39)
        self.module_40 = py_nndct.nn.Cat() #DeployV5::DeployV5/ret.85(DeployV5::nndct_concat_40)
        self.module_41 = py_nndct.nn.Conv2d(in_channels=102, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Sequential[fusion]/Conv2d[0]/ret.87(DeployV5::nndct_conv2d_41)
        self.module_42 = py_nndct.nn.ReLU(inplace=False) #DeployV5::DeployV5/Sequential[fusion]/ReLU[1]/ret.89(DeployV5::nndct_relu_42)
        self.module_43 = py_nndct.nn.Conv2d(in_channels=64, out_channels=9, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #DeployV5::DeployV5/Conv2d[direction_head]/ret(DeployV5::nndct_conv2d_43)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_1 = self.module_1(input=args[1])
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_0 = self.module_5(output_module_0)
        output_module_0 = self.module_6(output_module_0)
        output_module_0 = self.module_7(output_module_0)
        output_module_0 = self.module_8(output_module_0)
        output_module_0 = self.module_9(output_module_0)
        output_module_0 = self.module_10(output_module_0)
        output_module_0 = self.module_11(output_module_0)
        output_module_0 = self.module_12(output_module_0)
        output_module_1 = self.module_13(output_module_1)
        output_module_1 = self.module_14(output_module_1)
        output_module_1 = self.module_15(output_module_1)
        output_module_1 = self.module_16(output_module_1)
        output_module_1 = self.module_17(output_module_1)
        output_module_1 = self.module_18(output_module_1)
        output_module_1 = self.module_19(output_module_1)
        output_module_1 = self.module_20(output_module_1)
        output_module_1 = self.module_21(output_module_1)
        output_module_1 = self.module_22(output_module_1)
        output_module_1 = self.module_23(output_module_1)
        output_module_0 = self.module_24(dim=1, tensors=[output_module_0,output_module_1])
        output_module_0 = self.module_25(output_module_0)
        output_module_0 = self.module_26(output_module_0)
        output_module_27 = self.module_27(output_module_0)
        output_module_27 = self.module_28(output_module_27)
        output_module_27 = self.module_29(output_module_27)
        output_module_30 = self.module_30(output_module_0)
        output_module_30 = self.module_31(output_module_30)
        output_module_30 = self.module_32(output_module_30)
        output_module_33 = self.module_33(output_module_0)
        output_module_33 = self.module_34(output_module_33)
        output_module_33 = self.module_35(output_module_33)
        output_module_36 = self.module_36(output_module_0)
        output_module_36 = self.module_37(output_module_36)
        output_module_36 = self.module_38(output_module_36)
        output_module_36 = self.module_39(output_module_36)
        output_module_40 = self.module_40(dim=1, tensors=[output_module_0,output_module_30,output_module_33])
        output_module_40 = self.module_41(output_module_40)
        output_module_40 = self.module_42(output_module_40)
        output_module_40 = self.module_43(output_module_40)
        return (output_module_27,output_module_30,output_module_33,output_module_36,output_module_40)
